# Generated by Django 3.1.7 on 2021-03-30 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата')),
                ('title', models.CharField(max_length=255, verbose_name='Название События')),
                ('event_type', models.CharField(max_length=255, verbose_name='Тип События')),
                ('price', models.CharField(blank=True, max_length=255, null=True, verbose_name='Цена')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='full')),
                ('ticket_link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на покупку')),
                ('event_link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на объявление')),
            ],
        ),
    ]
