# Generated by Django 3.1.2 on 2021-04-01 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Событие', 'verbose_name_plural': 'События'},
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('Планетарий', 'Планетарий'), ('Спектакли', 'Спектакли'), ('Концерты', 'Концерты'), ('Фестивали', 'Фестивали'), ('Спорт', 'Спорт'), ('Детям', 'Детям'), ('Шоу', 'Шоу'), ('Юмор', 'Юмор'), ('Кино', 'Кино'), ('Другое', 'Другое')], max_length=255, verbose_name='Тип События'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(upload_to='logo', verbose_name='Изображение'),
        ),
    ]
