version: '3.8'

services:
  web:
    build: .
    container_name: EventsBot
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres
    container_name: events_bot_db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/db_data/
    environment:
      - POSTGRES_DB=EventsBot
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432

volumes:
  postgres_data:



