version: '3.8'

services:
  web:
    build: .
    container_name: EventsBot
    command: >
      bash -c "python /code/manage.py migrate --noinput &&
      python /code/manage.py collectstatic --noinput &&
      celery -A EventsProject worker -l INFO --logfile=/tmp/celery.log --detach &&
      celery -A EventsProject beat -l INFO --logfile=/tmp/celery-beat.log --detach &&
      gunicorn EventsProject.wsgi:application -b 0.0.0.0:8001 --reload"
    volumes:
      - .:/code/
    ports:
      - "8001:8001"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres
    container_name: events_bot_db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/db_data/
    environment:
      - POSTGRES_DB=EventsBot
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - 5432
  redis:
    image: redis

volumes:
  postgres_data:
